name: Node.js push on master branch

on:
  push:
    branches: [master]

env:
  WEBSITE_URL: https://plandar.nl

jobs:
  sonar:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04

    #     Run the steps in a Docker container on the virtual machine
    container:
      image: node:12.16.2
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    # Run the steps in a Docker container on the virtual machine
#    container:
#      image: node:12.16.2
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      - name: Get configuration
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./src/config.json --decrypt ./src/config.json.gpg

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: npm ci
      # Build the project
      - name: Build
        run: npm run build --if-present
      # Test the project
      - name: Test
        run: npm test
        env:
          CI: true
      # Upload the release folder and Dockerfile artifacts to this GitHub workflow for use in the next job
      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-artifact
          path: ./build
      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile
  deliver:
    needs: [build, sonar]
    runs-on: ubuntu-18.04
    steps:
      # Download artifacts from GitHub workflow to use in this job
      - name: Download release artifact
        uses: actions/download-artifact@v1
        with:
          name: release-artifact
          path: ./build
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v1
        with:
          name: dockerfile-artifact
          path: .
      # Deliver Docker image to Github packages
      - name: Deliver Docker image
        env:
          CONTAINER_IMAGE: docker.pkg.github.com/ese6-individual-project-floris-feddema/webservice/webservice:${{ github.sha }}
          CONTAINER_IMAGE_LATEST: docker.pkg.github.com/ese6-individual-project-floris-feddema/webservice/webservice:latest
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_GITHUB_USERNAME }} --password-stdin
          docker build -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
          docker push $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE_LATEST

  lighthouse-check:
    needs: deploy
    runs-on: ubuntu-18.04
    name: Lighthouse check
    steps:
      - name: Run Lighthouse check
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ env.WEBSITE_URL }}

#  zap-scan:
#    needs: deploy
#    runs-on: ubuntu-18.04
#    name: OWASP ZAP Baseline scan
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Run OWASP ZAP baseline scan
#        uses: zaproxy/action-baseline@v0.3.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          docker_name: 'owasp/zap2docker-stable'
#          target: ${{ env.WEBSITE_URL }}
#          rules_file_name: 'zaprules.tsv'